services:
  neo4j:
    image: neo4j:4.4
    volumes:
      - ./data/neo4j:/data
      - ./data/logs:/logs
    # exposed locally to use with ssh -L 7474:127.0.0.1:7474 -L 7687:127.0.0.1:7687 funky.wtf
    ports:
      - 127.0.0.1:7474:7474
      - 127.0.0.1:7687:7687
    environment:
      NEO4J_dbms_allow__upgrade: "true"
    restart: on-failure
    networks:
      - internal

  backend:
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.services.funky-api.loadbalancer.server.port=3000"
      - "traefik.http.routers.funky-api.rule=(Host(`funky-clan.de`) || Host(`www.funky-clan.de`) || Host(`funky.wtf`) || Host(`www.funky.wtf`)) && (PathPrefix(`/api`) || PathPrefix(`/socket.io`))"
      - "traefik.http.routers.funky-api.entrypoints=websecure"
      - "traefik.http.routers.funky-api.tls=true"
      - "traefik.http.routers.funky-api.tls.certresolver=le"
      - "traefik.http.routers.funky-api.priority=100"
    restart: on-failure
    networks:
      - internal
      - traefik

networks:
  internal:
    driver: bridge
  traefik:
    external: true
    name: traefik_default