version: '3.8'

services:
  neo4j:
    image: neo4j:4.4
    volumes:
      - ./data/neo4j:/data
      - ./data/logs:/logs
    # exposed locally to use with ssh -L 7474:127.0.0.1:7474 -L 7687:127.0.0.1:7687 funky.wtf
    ports:
      - 127.0.0.1:7474:7474
      - 127.0.0.1:7687:7687
    environment:
      NEO4J_dbms_allow__upgrade: "true"
    restart: on-failure

  backend:
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - 127.0.0.1:3000:3000
    restart: on-failure